### ISSUE TITLE
Object's due date returns wrong value

### ISSUE THREAD

**Issue by ransome1** [jmhobbs/jsTodoTxt#21] opened 2020-10-23 17:30 UTC
HI there.

If I was any good at regex at all I swear I would fix it and provide a pull request, but regex is like latin to me and I won't touch it.

Anyway, I was trying to work with the due date that jsTodoTxt provides me for an item in a todo.txt file.

In the file it's written down like this: 
<a href="https://imgur.com/4ZO538u.png">
  <img src="https://imgur.com/4ZO538u.png" />
</a>

The jsTodoTxt object returns this:
<a href="https://imgur.com/foFQdO0.png">
  <img src="https://imgur.com/foFQdO0.png" />
</a>

So for the completion date, everything is working fine. 2020-11-11 is read as the 11th of November of 2020.

But looking at the due date you can see that 2020-11-11 is being interpreted as 11th of December 2020.

Could you please take a quick look it at?

Best
ran

**Comment by adityabhaskar** [comment] 2020-10-23 17:49
The issue is here:

https://github.com/jmhobbs/jsTodoTxt/blob/bc6238ebb31e895fb257af3dd722223e9e248228/jsTodoExtensions.js#L38-L44

There is an off by one error when creating the date. The `new Date(...)` method counts months on a 0 basis (January = 0), so it converts the due date incorrectly.

This error occurs for due dates only because they are parsed separately in [jsTodoExtensions.js](https://github.com/jmhobbs/jsTodoTxt/blob/develop/jsTodoExtensions.js), while the other dates (creation, completion) are parsed correctly in [jsTodoTxt.js](https://github.com/jmhobbs/jsTodoTxt/blob/develop/jsTodoTxt.js).

You can correct it and submit a PR, or I will some time next week.

Hope this helps.

Cheers!

**Comment by xuhcc** [comment] 2020-10-23 19:43
It was fixed in #18

In my fork there's a branch that contains this and other fixes: https://github.com/xuhcc/jsTodoTxt/tree/fork
I think I can publish it as NPM package if you want.

**Comment by jmhobbs** [comment] 2020-10-23 20:42
Not sure how I missed that PR, @xuhcc, sorry about that.

**Comment by jmhobbs** [comment] 2020-10-23 20:58
Released that on 0.8.1 and 0.7.2.

**Closed** 2020-10-30 15:11 UTC
